### ISSUE TITLE
nss_wrapper does not work in 32-bit JVM

### ISSUE THREAD

**Issue by cliffred** [openshift/jenkins#1090]
Whenever the Jenkins slave uses a 32-bit JVM nss_wrapper does not work and the following error is shown.
`ERROR: ld.so: object 'libnss_wrapper.so' from LD_PRELOAD cannot be preloaded: ignored.`
This causes Java to look in the regular /etc/passwd which does not contain a 'default' entry for the generated user id. Therefore `System.getProperty("user.home")` returns `?`.

I am using Openshift 3.11 and the problem occurs since _openshift3/jenkins-slave-base-rhel7:v3.11.188_; which uses nss_wrapper instead of appending directly to the _/etc/passwd_ file from the _/usr/local/bin/generate_container_user_ script, see ebef7b81ac057a6a6fe7b3e4759656a4fcc570e0.

**Comment by akram** [comment]
Hi @cliffred , thanks for reporting this.
we (re-)introduced nss_wrapper because of a security issue and indeed that makes the image dependant on the platform  architecture it has been built on.
Do you have the ability to try to build it on a x86 32bits arch? this should pull nss_wrapper for this archictecture insteand of the x86_64 one.

as another workaround, can you try setting HOME env var in your jenkins deploymentconfig to see if it works for you?

**Comment by cliffred** [comment]
Hi @akram,
Thanks for the suggestions. I worked around it by setting `OPENSHIFT_JENKINS_JVM_ARCH` to `x86_64` to always run on a 64-bit JVM, regardless of the memory limit.
The `HOME` env var does not influence the output of `System.getProperty("user.home")` in Java, so that doesn't work unfortunately.

As there are workarounds for this issue, and because of the necessity of nss_wrapper regarding security, I think this issue could be closed.

**Comment by akram** [comment]
Thanks
/close
