### ISSUE TITLE
Failed to download plugin with provided INSTALL_PLUGINS

### ISSUE THREAD

**Issue by gloria-zmm** [openshift/jenkins#1446]
Hi,
We are using OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS=true and INSTALL_PLUGINS={list of plugins} to install plugins during jenkins start up. We encountered this issue:
```
Downloading plugins...
Using provided plugin: ace-editor
 > ace-editor has no dependencies
Downloading plugin: analysis-model-api from https://updates.jenkins.io/download/plugins/analysis-model-api/10.9.1/analysis-model-api.hpi
Downloading plugin: analysis-model-api-plugin from https://updates.jenkins.io/download/plugins/analysis-model-api-plugin/10.9.1/analysis-model-api-plugin.hpi
Failed to download plugin: analysis-model-api or analysis-model-api-plugin
```
It happened at a very high frequency. Usually after several times of restart it can run successfully finally.
The image we are using is :
registry.redhat.io/openshift4/ose-jenkins:v4.9.0-202202080146.p0.ga71a115.assembly.stream

Please suggest us what to do to improve the efficiency.

**Comment by chengjun0124** [comment]
Hi
I suffered the same issue. The issue is intermittent.

**Comment by chengjun0124** [comment]
The issue is caused by network issue. When jenkins tries to download plugin, the network is not ready.  

It is not an issue from openshift jenkins. Openshift jenkins uses parameter `--retry` of curl to make sure a successful download:
`curl $curl_options --connect-timeout "${CURL_CONNECTION_TIMEOUT:-20}" --retry "${CURL_RETRY:-5}" --retry-delay "${CURL_RETRY_DELAY:-0}" --retry-max-time "${CURL_RETRY_MAX_TIME:-60}" -s -f -L "$url" -o "$jpi"`.
However `--retry` only retries for HTTP 408, 429, 500, 502, 503 or 504 response code.

From fault-tolerance perspective, I would be better if openshift jenkins were to retry download against other network issues, like `curl: (7) couldn't connect to host`.

**Comment by akram** [comment]
@chengjun0124 could you please propose a fix through a PR? 
Network flakes and issues can be of a different types, so we still have choice on what to test. And testing on every iteration of download may be unproductive. what do you think?

**Comment by ggareth** [comment]
The issue I was having was not with a flakey network, but with mirrors not being complete. 
Have proposed a PR which reduces (makes it work for me) the effects

**Comment by coreydaley** [comment]
We have added the ability to retry downloads when they fail which should help with this.
/close
