### ISSUE TITLE
[sync-plugin] - 404 on Jenkins logs and job in Jenkins

### ISSUE THREAD

**Issue by tnozicka** [openshift/jenkins#146]
Steps to reproduce.
1. $ oc cluster up --version=v1.3.0-alpha.3
2. $ oc process -f https://github.com/tnozicka/nodejs-ex/raw/kontinu8-next/.openshift-pipeline/pipeline-template.yaml -v 'GIT_URL=https://github.com/tnozicka/nodejs-ex.git,GIT_REF=kontinu8-next' | oc apply -f -
3. $ oc start-build nodejs-ex-pipeline
4. $ oc process -f https://github.com/tnozicka/nodejs-ex/raw/sync-WIP/.openshift-pipeline/pipeline-template.yaml -v 'GIT_URL=https://github.com/tnozicka/nodejs-ex.git,GIT_REF=sync-WIP' | oc apply -f -

Now try looking at the job in Jenkins or try viewing it's logs in Jenkins. You will get 404 there. You won't also see the job in Jenkins's overview, but you will see it a running build executor for it.

@jimmidyson

**Comment by bparees** [comment]
this sounds like the issue where the buildconfig was getting mistakenly deleted when you applied changes to it, which was fixed by fix to also not delete builds when the jenkins server started up.

I ran your steps as best i could and i still see a job under `job/nodejs-ex-pipeline/1/` from when i ran "oc start-build" in step 3.

**Comment by bparees** [comment]
(in case my comment wasn't clear, i guess i'm asking you to confirm you're running the latest jenkins image and/or think if there are any other steps that might be part of the recreate)

**Comment by tnozicka** [comment]
@bparees I believe I have deleted all the images today, so the problem isn't most probably there.
```
docker.io/openshift/jenkins-1-centos7                    <none>              b0e35f71bbff        2 days ago
```
I could add the urls that are not working and some screenshots next week. Only other thing might be timing. (I have run all those steps with max. 2s delay)

Also note that step 2. and 4. are different so the sync plugin might delete the config and create new one resulting in those problems.

**Comment by bparees** [comment]
@tnozicka we'll need @jimmidyson to weigh in, but he's on PTO.  @iocanel might be able to help in his absence.  But i tried a few times and can't recreate the behavior you're seeing.  I definitely need to see the URLs you are saying exist before and not after the buildconfig change, but for me both the job url, and the job instance urls, continue to resolve both before and after step 4.

i'd also be interested to know what happens if you just "oc edit" the buildconfig and apply changes that way.

**Comment by bparees** [comment]
@tnozicka is this still an issue for you?

**Comment by tnozicka** [comment]
@bparees it seems to be working with `v1.5.0-alpha.2+e4b43ee-dirty` so I am closing it as "no longer an issue"
