### ISSUE TITLE
Keep slave build cache

### ISSUE THREAD

**Issue by gianluca-sabena** [openshift/jenkins#262]
Is it possible to keep dependent libraries and intermediate compilated files between multiple run of a build job?

I'm working on a sbt slave to compile a scala project. Sbt is really slow on first dependency resolution, so I need to keep sbt data cace between multiple run. 

My first idea is to enable persitent storage on slave pods. A second approach is to zip the cache and store on the master with some jenkins plugin/feature. 

Is this feature already implemented?

Thanks

**Comment by bparees** [comment]
persistent storage on the slaves probably won't work since a new slave pod is created every time the job is run so i'm not sure if you how you can ensure the same volume gets reused for every slave pod (but i'm not an expert in the storage aspects of openshift, so it might be possible)

running the job directly on the master would be one option, or as you say zipping the cache and storing it on the master.

you could also stand up a long running slave pod instead of using the cloud plugin.

But short answer: there is no openshift/kubernetes specific support/feature for this, only whatever the jenkins ecosystem offers.

**Comment by gianluca-sabena** [comment]
I have a use case that requires to scale builds, and so to add cache support to slave is very important. I suggest to keep this issue open and tag it as "new feature/improvements"

If I understood correctly, jenkins uses kubernetes plugin that has volume support https://github.com/jenkinsci/kubernetes-plugin#pod-and-container-template-configuration

My idea is:
- modify kubernates plugin and add persistent volumes support
- use something like job-name to namespace cache inside volume 

Thanks

**Comment by gianluca-sabena** [comment]
Example of custom jenkins slave with sbt and persistent storage https://github.com/gianluca-sabena/orchestration-playground/blob/master/docs/openshift.md#jenkins
