### ISSUE TITLE
Frequently hitting oom

### ISSUE THREAD

**Issue by andrewklau** [openshift/jenkins#302]
After updating, my Jenkins server is frequently hitting OOM and crashing. It seems to be Java reporting the OOM rather then Docker enforcing the quota. Metrics are reporting it only maxes out at 1.3GB but it's allocated 2GB. 

Perhaps this change may be the culprit https://github.com/openshift/jenkins/commit/8afc4f8d62aaafcd5fc407c30c4ebe4dcb3d869b

When using an earlier version, before importing the updated image, it would run fine with 1GB used and 2GB available

**Comment by bparees** [comment]
> Metrics are reporting it only maxes out at 1.3GB but it's allocated 2GB.

that's what, container usage?

> When using an earlier version, before importing the updated image, it would run fine with 1GB used and 2GB available

we did tune the system to be more conservative in terms of heap size, in order to reserve more memory for native usage.  This is because a JVM that runs out of heap is easy to debug, a system that crashes and burns because it tried to allocate native memory that wasn't available is hard to debug.

If you're confident your use case can run successfully with more heap (and thus less native memory), you can tune the CONTAINER_HEAP_PERCENT variable to allocate more of the container memory to heap.

**Comment by andrewklau** [comment]
> that's what, container usage?
container usage was at 1.3GB but it's max (resource limit) was 2GB. So it was getting killed due to the failed healthcheck rather than the Docker container oom 

Thanks, `CONTAINER_HEAP_PERCENT` was what I was looking for.

**Comment by bparees** [comment]
great.
