### ISSUE TITLE
Dockerfile registry path needs updating

### ISSUE THREAD

**Issue by ferozeb** [openshift/jenkins#313]
Its seems that the openshift/jenkins-slave-base-rhel7 needs to be openshift3/jenkins-slave-base-rhel7.

And it seem the follow will need to be removed from the Dockerfile,

    rpm -e java-1.7.0-openjdk --nodeps || true && \
    rpm -e java-1.7.0-openjdk-devel --nodeps || true && \
    rpm -e java-1.7.0-openjdk-headless --nodeps || true && \

**Comment by bparees** [comment]
> Its seems that the openshift/jenkins-slave-base-rhel7 needs to be openshift3/jenkins-slave-base-rhel7.

this is related to how we build the image internally on our CI system.  We can see about aligning the internal and external image names, but for now that's why it is this way.

> And it seem the follow will need to be removed from the Dockerfile,

those are there because the maven package is incorrectly dragging in java1.7 as a dependency, so we need to remove it (the || true is so the remove doesn't start causing failures when the maven package is fixed).  Are you saying the maven package has been fixed?  I haven't checked lately.
