### ISSUE TITLE
Allow more fine-grained control for adding/updating plugins using s2i method when using Jenkins PV

### ISSUE THREAD

**Issue by scoheb** [openshift/jenkins#335]
Scenario: Provide more control to update plugins on already configured Jenkins instance
Given a Jenkins instance created using the s2i method
And the s2i config contains a plugins.txt file
And the instance is configured using a PV
And the instance has been initially deployed to create JENKINS_HOME on PV
When the image is updated to include a update to plugins.txt to add/update a plugin
And the s2i builder is configured to use OVERRIDE_EXISTING_PLUGINS
Then the images' plugins are used instead of the already existing plugin set in JENKINS_HOME in PV

**Comment by bparees** [comment]
@gabemontero we should look at everything we do/do not copy when the PV is already "configured" and make each type of content (plugins, config, anything else?) individually configurable as "overwrite existing" or not.

**Comment by gabemontero** [comment]
@bparees shall we create a trello card for this as well, or do you want to handle outside of sprint planning?

**Comment by bparees** [comment]
@gabemontero i don't think we need a card for this, it should be pretty trivial.

**Comment by gabemontero** [comment]
As of this comment, an inventory of various config related activites:

1) Dockerfile / docker build
    - oc binary is copied to /usr/local/bin
    - base-plugins.txt and password-encoder.jar are copied to /opt/openshift
    - config.xml.tpl, credentials.xml.tpl, the openshift sample job config, disabling of SSHD via its xml config file,  and the admin user config (for when oauth is disabled) are copied to /opt/openshift/configuration
    - fix-permissions, install-plugins.sh, jenkins-common.sh, and kube-slave-common.sh are copied to /usr/local/bin
    - the s2i assemble and run scripts are copied to  /usr/libexec/s2i
    - the default plugins are installed and various permissions are set so we can switch between 32 and 64 bit java

2) When the s2i run script is launched during jenkins startup, and the jenkins instance is considered "not yet configured" (i.e. JENKINS_HOME/configured or /var/lib/jenkins/configured does not exist), the following occurs:

   - if /opt/openshift/configuration/config.xml does not yet exist, it grabs the config.xml.tpl (copied over by the docker file) and generates a config.xml file, updating the k8s plugin config based on what is mounted in the pod, and if you have overridden the images used for the slave, and the jnlp service, via env vars

   - if /opt/openshift/configuration/credentials.xml does not yet exist, it grabs the credentials.xml.tpl (copied over by the docker file) and generates credentials.xml for the k8s SA (no env var overrides)

   - the xml files, admin user creds, and sample job are copied to /var/lib/jenkins / JENKINS_HOME

   - the INSTALL_PLUGINS env var is processed, installing plugins noted in that env var (@scoheb's specific scenario)

   - the actual creation of the admin user

3) Independent of the "configured" flag, if the config.xml.tpl exists, and the config.xml file has somehow been removed, the config.xml is regenerated

4) Independent of the "configured" flag, various env vars for 32bit vs. 64bit, java opts/args, jenkins opts/access logs

5) Independent of the "configured" flag, set up of env vars related to options for running the `oc` command with the token/certs mounted in the pod

**Comment by gabemontero** [comment]
@bparees for config related overrides, do we just allow the user to specify the new contents in an env var? if so, does that include the config.xml/credentials.xml and their template based approach wrt substituting other env vars or items mounted into the pod?

**Comment by gabemontero** [comment]
Or perhaps just duplicate this existing pattern:

```
if [ -f "${CONFIG_PATH}.tpl" -a ! -f "${CONFIG_PATH}" ]; then
  echo "Processing Jenkins configuration (${CONFIG_PATH}.tpl) ..."
  envsubst < "${CONFIG_PATH}.tpl" > "${CONFIG_PATH}"
fi
```

**Comment by gabemontero** [comment]
Yeah I actually like that pattern ... no additional env vars required, simply recreate the paths/files cleared out after initially configuring ... will submit PR in a bit

**Comment by bparees** [comment]
@gabemontero first off, the stuff being copied in the Dockerfile is/are irrelevant.

The issue here is a user does the following:

1) user starts up jenkins with a PV bound.  We generate/copy the config into the PV and also copy the plugins from the image to the PV

2) user modifies their jenkins image (builds a new one) with different config/plugins

3) the jenkins pod restarts to pick up the new image.  It ignores the changes to the config/plugins because the PV is already "configured".

The desired behavior is to provide an option where the user can say "always copy X from the image into the PV, even if the PV has been previously initialized".  Where X would be things like "the config.xml" "the plugins", "the credentials.xml", etc.

What I was expecting to see in the PR was something like:

if -f /path/to/pv/configured && !ALWAYS_USE_IMAGE_PLUGINS {
  wipe out PV plugins dir and replace with image plugins
}

if -f /path/to/pv/configured && !ALWAYS_USE_IMAGE_CONFIG_XML {
  wipe out PV config.xml and replace with image config.xml or generated config.xml from template
}

etc for other things we want to allow to be replaced on the PV w/ the content from the image.

**Comment by bparees** [comment]
Note that "always using image content" should not be the default for any content item (the default should continue to be "use what's in the PV, if the PV has been initialized already")

**Comment by gabemontero** [comment]
On Thu, Aug 3, 2017 at 2:15 PM, Ben Parees <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero> first off, the stuff being
> copied in the Dockerfile is/are irrelevant.
>
I expanded the background beyond what was specifically relevant just for my
own understanding.  Apologies if
it caused undo clutter, etc.

> The issue here is a user does the following:
>
>    1.
>
>    user starts up jenkins with a PV bound. We generate/copy the config
>    into the PV and also copy the plugins from the image to the PV
>    2.
>
>    user modifies their jenkins image (builds a new one) with different
>    config/plugins
>    3.
>
>    the jenkins pod restarts to pick up the new image. It ignores the
>    changes to the config/plugins because the PV is already "configured".
>
> The desired behavior is to provide an option where the user can say
> "always copy X from the image into the PV, even if the PV has been
> previously initialized". Where X would be things like "the config.xml" "the
> plugins", "the credentials.xml", etc.
>
Yes, understood.  I believe the PR is in fact doing that.

> What I was expecting to see in the PR was something like:
>
> if -f /path/to/pv/configured && !ALWAYS_USE_IMAGE_PLUGINS {
> wipe out PV plugins dir and replace with image plugins
> }
>
> if -f /path/to/pv/configured && !ALWAYS_USE_IMAGE_CONFIG_XML {
> wipe out PV config.xml and replace with image config.xml or generated
> config.xml from template
> }
>
> etc for other things we want to allow to be replaced on the PV w/ the
> content from the image.
>
It dawned on my that since the "configured" path is removing the files from
the image that it copied into the PV,
we could leverage the presence of the files in those spots as the trigger,
and not NEED the use of these env vars
to trigger the behavior.

Hence if the user has not repopulated those dirs, what was put it the PV on
initial start up should be what is taken
on subsequent startups.

If you think that won't work, I'm missing something then. Bang my head as
needed then.

**Comment by bparees** [comment]
1) How are you allowing a user to choose whether they want to revert to what is in the image, or continue using the content from the PV?

2) You're checking for the presence of the config files in the PV path(/var/lib/jenkins), so your logic will never execute anyway unless the user removes the content from their PV (and puts a tpl file there)

3) The content that the "first time configure path" removes will be repopulated on every restart of the container since that content is part of the image.  (there's really no good reason for the configuration code path to be removing those files, it accomplishes nothing), so in the case where you are looking to see if /opt/openshift/plugins is populated, it always will be, so you're always going to restore the plugin content from the image (the opposite of the current default behavior)
