### ISSUE TITLE
error: mkdir /var/lib/origin/openshift.local.config: permission denied

### ISSUE THREAD

**Issue by slinger-scm** [openshift/jenkins#361]
Hello guys!
I'm having this issue while trying to execute my pipeline, any idea I saw that has a push to dockerhub 4 days ago in the image that my pipeline use as slave.. https://hub.docker.com/r/openshift/jenkins-slave-nodejs-centos7/tags/

```
OpenShift Build tasks-pipeline13
[Pipeline] node
Still waiting to schedule task
All nodes of label ‘nodejs’ are offline
Running on nodejs-69e36c499aac1 in /tmp/workspace
[Pipeline] {
[Pipeline] sh

[cicd] Running shell script

oc project cicd
error: mkdir /var/lib/origin/openshift.local.config: permission denied
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
ERROR: script returned exit code 1
Finished: FAILURE
```

**Comment by bparees** [comment]
can you share the pod logs from the slave pod that got spun up (nodejs-69e36c499aac1)?

also if you can share your jenkinsfile/pipeline definition that could help.

**Comment by maiconbaumx** [comment]
Hello @bparees! That post wast initiated from my second account, the @slinger-scm.
This issue was present in the latest jenkins-slave-nodejs-centos7 image from OpenShift's Dockerhub repository. After several tries, I decided to build a new Jenkins Slave image from this Dockerfile and use for my pipeline. I don't have these logs anymore, but this error appears in the logs.. After build a new image and giving the /var/lib/jenkins directory permission for write  of user 1001, everything works fine... My JenkinsFile:



node('nodejs') {
   def sourceCode = "xx"
   def webhook = "xx"
   def application = "xx"
   def urlDev = "xx"
   def urlProd = "xx"
   def secret = "xx"
   def projectDEV = "xx"
   def projectPROD = "xx"
   def webhookDEV = "xx"
   def webhookPROD = "xx"

   stage 'Clean'
   sh "oc project $projectDEV"
   sh "oc delete bc,dc,svc,route -l app=${application} -n $projectDEV"

   stage 'Build'
   pauseAlert(true,3)
   git branch: "master", credentialsId: 'xx', url: 'xx'
   def v = version()
   sh "curl -X POST -H 'Content-Type: application/json' --data '{\"username\":\"CI/CD\",\"icon_url\":\":bellhop:\",\"text\":\"Deploy da aplicação $application iniciado em $projectDEV!\",\"attachments\":[{\"title\":\"xx\",\"text\":\"Deploy da aplicação $application iniciado em $projectDEV!\"}]}' $webhookDEV"
   sh "oc create -f $secret -n $projectDEV || true"
   sh "oc new-build s2i-nodejs:6.10.3~$sourceCode --name=$projectDEV --labels=app=xx -n $projectDEV || true"
   sh "oc patch buildConfig $projectDEV  -p '{\"spec\":{\"source\":{\"sourceSecret\":{\"name\":\"sshsecret\"}}}}' -n $projectDEV"
   sh "oc start-build $projectDEV --git-repository=$sourceCode --wait=true -n $projectDEV"

   stage 'Deploy Desenvolvimento'
   sh "oc new-app $projectDEV --name=${application} -n $projectDEV"
   sh "oc expose svc/$application --hostname=xx -n $projectDEV"
   sh "curl -X POST -H 'Content-Type: application/json' --data '{\"description\":\"Deploy da aplicação dev-$application:$v realizado!\"}' $webhook/$projectDEV"
   pauseAlert(false,3)
   
   stage 'Deploy Produção'
   input message: "Promover para produção?", ok: "Promover"
   pauseAlert(true,2)
   sh "curl -X POST -H 'Content-Type: application/json' --data '{\"username\":\"CI/CD\",\"icon_url\":\":bellhop:\",\"text\":\"Deploy da aplicação $application iniciado em $projectDEV!\",\"attachments\":[{\"title\":\"xx\",\"text\":\"Deploy da aplicação $application:$v iniciado em $projectPROD!\"}]}' $webhookPROD"
   sh "oc project $projectPROD"
   sh "oc tag $projectDEV/$projectDEV:latest $projectPROD/$projectPROD:${v}"
   sh "oc delete bc,dc,svc,route -l app=$application -n $projectPROD"
   sh "oc new-app $projectPROD:$v --name=xx -n $projectPROD"
   sh "oc expose svc/$application --hostname=xx -n $projectPROD"
   sh "curl -X POST -H 'Content-Type: application/json' --data '{\"description\":\"Deploy da aplicação prod-$application:$v realizado!\"}' $webhook/$projectPROD"
   pauseAlert(false,2)

}

def version() {
  def matcher = readFile('package.json') =~ '"version": "(.+)",'
  matcher ? matcher[0][1] : null
}

def pauseAlert(state,id){
  sh "curl -H \"Authorization: Bearer xx=\" -H \"Content-Type: application/json\" -H \"Accept: application/json\" -X POST -d '{\"paused\":$state}' xx"
}

**Comment by bparees** [comment]
hm.  this seems like new behavior in the oc client.  I will loosen the permissions in the image like you did, though.  thanks!

@csrwng @gabemontero @fabianofranz are you aware of this change/breakage?  In particular I'd think @csrwng or @stevekuznetsov would have run into it...

**Comment by csrwng** [comment]
I have not run into this issue yet, but I am not calling 'oc project [name]' in any pipeline

**Comment by gabemontero** [comment]
On Tue, Aug 22, 2017 at 4:33 PM, Cesar Wong <notifications@github.com>
wrote:

> I have not run into this issue yet, but I am not calling 'oc project
> [name]' in any pipeline
>
Same on both points for me as well
