### ISSUE TITLE
curl: (60) Peer's Certificate issuer is not recognized.

### ISSUE THREAD

**Issue by cmoulliard** [openshift/jenkins#368]
As curl doesn't use as parameter the option -k - see [line](https://github.com/openshift/jenkins/blob/master/slave-base/contrib/bin/run-jnlp-client#L57) to download the remote.jar file, we will get this error when the jenkins slave pod will try to access the jenkins server

```
[root@n058 ~]# oc logs maven-6e0da1f6cbd0
Using 64 bit Java since OPENSHIFT_JENKINS_JVM_ARCH is not set
Downloading https://spring-boot-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/jnlpJars/remoting.jar ...
curl: (60) Peer's Certificate issuer is not recognized.
More details here: http://curl.haxx.se/docs/sslcerts.html
curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by bparees** [comment]
You can provide the cert bundle to your slave by defining it as a secret and updating the slave pod template to mount the secret to the correct path (or building your own slave image w/ the certs baked in) I don't think we want to set the -k option on curl because we want to be secure by default.  (though again, you can customize the image yourself to do that).
