### ISSUE TITLE
Simplify the support for maven, gradle and sbt

### ISSUE THREAD

**Issue by arnaud-deprez** [openshift/jenkins#375]
Hi,

I would like to react to what is been done in #298 and the comment from @jstrachan.

Usually gradle developer uses the [gradle wrapper](url), it allows developer to specify the gradle version they want to use + their location. This ensure a reproducible built on whatever machine you are as long you have access to the server where your gradle distribution resides.

More recently but yet 2 years ago, an equivalent [maven wrapper](https://github.com/takari/maven-wrapper) is born. However I know all maven developers are not use to it yet.

For scala, sbt works roughly in the same way thanks to [its launcher](https://github.com/sbt/launcher).

So my point here is : wouldn't it be simpler to create a jenkins-java-slave image configured to handle either maven, gradle or sbt project. 
* For gradle, we need to specify GRADLE_USER_HOME env variable, then it's up to people to define init scripts in $GRADLE_USER_HOME/init.d/. We can put a default that use the same MAVEN_MIRROR_URL for example
* For maven, we just need the settings.xml
* For sbt, I don't think we need anything

I think that would simplify the version management of all these tools letting the developer choose what to do.
Then if needed, we can still derive this image to add let say "an official supported version" of these tools.

What do you think ?

**Comment by bparees** [comment]
We need to ship images that contain content from known locations. So while what you suggest might be viable for the centos images, it's not viable for our rhel images to distribute an image that downloads content from arbitrary locations on the internet.  Furthermore the way these images are consumed (using an ephemeral filesystem), the "correct" gradle/maven version (assuming it's not one that's built into the image already) would have to be downloaded on every run of your job, which is going to be a pretty bad user experience.

We aren't going to curate the perfect set of slave images for all users(in the sense of providing all the exact tools+versions of those tools that users desire), the existing maven and nodejs slaves should really be thought of as examples/starting points for users to extend.  (or start from the slave-base image and extend that).

**Comment by arnaud-deprez** [comment]
Hi @bparees,

I understand what you mean but for example, for gradle in enterprise, we ususally provide the gradle distribution on the intranet. This distribution might be customized (it embedded initialization script) or not.
Moreover, these images download already dependencies in order to build the application. 
To improve the user experience for this, we use the archiveArtifacts that will basically cache a directory on the master. 
I think we could the same with gradle or maven too, couldn't we ?

**Comment by bparees** [comment]
> I understand what you mean but for example, for gradle in enterprise, we ususally provide the gradle distribution on the intranet. 

then you could also provide your own slave images w/ the custom gradle distribution built in.  (just extend the slave-base or slave-maven image)

> Moreover, these images download already dependencies in order to build the application.

sure, but that's driven by your pom.xml, not our image behavior.  So that's a user choice, not something we're forcing on the user.  (and from a performance perspective, everything you have to download is going to make the build take longer)

> To improve the user experience for this, we use the archiveArtifacts that will basically cache a directory on the master.
I think we could the same with gradle or maven too, couldn't we ?

i think it could probably work, but i'm not convinced it's going to be simpler or more supportable, so while I'd encourage you to pursue that avenue for your own jenkins slave image use, I don't know that we'd want to go that direction for the one we ship+support.  You're certainly welcome to fork this repo and develop your solution and submit a PR for us to consider, of course!

**Comment by arnaud-deprez** [comment]
I created #394 as an attempt to unified behaviour between gradle and maven. I'll go further with my idea later (when I'll have more time) on and get back here if success.
Thanks you,

**Comment by jstrachan** [comment]
in the age of docker images, it does feel that rather than having wrappers that install tarballs of tools on demand; we'd be better to referencing the versioned docker images directly in the kubernetes build pods.

e.g. we've moved away from using jenkins 'tools' which install versions of stuff from tarballs into slaves to versioned docker images in kubernetes build pods

**Comment by arnaud-deprez** [comment]
Thank you for your advices, I will forget this idea as I also meet other problems with it.
