### ISSUE TITLE
Why is user 1001 used?

### ISSUE THREAD

**Issue by yu2003w** [openshift/jenkins#410]
One question about the docker file.
"user 1001", why need to use this?
Could "user root" be used? 
Could you help to share design considerations?

Thanks very much.

**Comment by coreydaley** [comment]
@yu2003w From the OpenShift documentation:
"Lastly, the final USER declaration in the Dockerfile should specify the user ID (numeric value) and not the user name. This allows OpenShift Origin to validate the authority the image is attempting to run with and prevent running images that are trying to run as root, because running containers as a privileged user exposes potential security holes. If the image does not specify a USER, it inherits the USER from the parent image."


https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines

**Comment by bparees** [comment]
Also when you actually run the jenkins image(or any image) on openshift it's going to run as a random uid anyway (not necessarily 1001 and definitely not root), unless you have changed the default configuration or granted additional permissions.
