### ISSUE TITLE
Include Blue Ocean in the default plugins for the master

### ISSUE THREAD

**Issue by sherl0cks** [openshift/jenkins#426]
Since blueocean is the future of Jenkins UX, it would be good to include it by default. In particular, because there can be interesting issues with plugin versions between blueocean and some OCP plugins like the sync plugin.

Any interest? I'd be happy to submit a PR on this.

**Comment by bparees** [comment]
it is included by default already:
https://github.com/openshift/jenkins/blob/master/2/contrib/openshift/base-plugins.txt#L36

**Comment by bparees** [comment]
@gabemontero you're not aware of us having regressed anything on this front, are you?

**Comment by bparees** [comment]
confirmed blue ocean ui is available in our image.

**Comment by sherl0cks** [comment]
looks like I'm late to the party and all of this has been handled.

1.1.7 is the latest version that is working correctly according to our testing, so 1.1.6 should be fine. there was issue opened here with the blueocean folks and they were looking for collab on these items in the future, as anything > 1.2.0 still doesnt work and blue ocean is 1.3.x right now.

https://issues.jenkins-ci.org/browse/JENKINS-47637

looks like https://github.com/openshift/jenkins/pull/387 handled the issue correctly here

**Comment by bparees** [comment]
@gabemontero sounds like we'll have to investigate https://issues.jenkins-ci.org/browse/JENKINS-47637 when we get ready to update to a newer blueocean plugin :(

**Comment by gabemontero** [comment]
On Thu, Nov 30, 2017 at 5:28 PM, Ben Parees <notifications@github.com>
wrote:

> @gabemontero <https://github.com/gabemontero> you're not aware of us
> having regressed anything on this front, are you?
>
no, it works .... just oc clustered up with the latest image and hit
https://jenkins-myproject.127.0.0.1.xip.io/blue/organizations/jenkins/pipelines
(i.e. the Open BlueOcean link on the left panel)
on my local system and it works

when you just login to jenkins, it is still the classic view

if there is some other entryway into blueocean I am unware of it; this is
how we've always accessed blueocean
since we pulled in the plugin

**Comment by sherl0cks** [comment]
@gabemontero that is the normal entrypoint for blueocean for now. as discussed above, the changes currently in master and 3.7 branch of this repo should be sage since the current blue ocean version is 1.1.6. If you upgrade past 1.1.7, you will hit  https://issues.jenkins-ci.org/browse/JENKINS-47637

**Comment by bparees** [comment]
@coreydaley can you please look into https://issues.jenkins-ci.org/browse/JENKINS-47637 as part of your jenkins techdebt work this sprint?  It would be nice for us to able to upgrade the blue ocean plugin.

**Comment by sherl0cks** [comment]
looks like @gabemontero was working this as part of:
https://issues.jenkins-ci.org/browse/JENKINS-42276
https://github.com/openshift/jenkins-sync-plugin/pull/184 

Doesn't appear that a new version of the plugin has been released though: https://plugins.jenkins.io/openshift-sync

**Comment by gabemontero** [comment]
On Thu, Nov 30, 2017 at 8:35 PM Justin Holmes <notifications@github.com>
wrote:

> looks like @gabemontero <https://github.com/gabemontero> was working this
> as part of:
> https://issues.jenkins-ci.org/browse/JENKINS-42276
> openshift/jenkins-sync-plugin#184
> <https://github.com/openshift/jenkins-sync-plugin/pull/184>
>
> Doesn't appear that a new version of the plugin has been released though:
> https://plugins.jenkins.io/openshift-sync
>
that was on the to do list for today since 3.7 shipped but we ended up
having to fire fight some post GA issues.

Should be coming soon

**Comment by sherl0cks** [comment]
I'm familiar =). I'll make it a priority to test the prelease build that is in the ticket to at least confirm it resolves the issue we have been seeing, hopefully getting you that feedback ahead of a new release.

**Comment by coreydaley** [comment]
@bparees added it to my list

**Comment by gabemontero** [comment]
OK, I actually had a sec to read all the referenced info and caught up.

So yeah, I started looking at https://issues.jenkins-ci.org/browse/JENKINS-42276 toward the tail end of 3.7.  From the other jira's referenced (this injection thing impacted several plugins), the removal of the extraneous save() call in the config descr null ctor was a safe bet for a root cause.  Also, it was a safe change in that it was not needed.  Actual config changes would be saved in the ctor with params.

That said, when trying to vet things, as noted in https://github.com/openshift/jenkins-sync-plugin/pull/184, I manually upgraded blueocean and could not recreate the issue, even when also upgrading some of the other plugins noted in the various issues/jira's.

At this point, I think the next steps are:
- I'm planning on cutting the first post 3.7 plugin versions next week, once the 3.7 GA noise is sufficiently calms down and @bparees and I feel comfortable
- if @coreydaley can take another crack and trying to reproduce https://issues.jenkins-ci.org/browse/JENKINS-42276 with a sync plugin version which does not have https://github.com/openshift/jenkins-sync-plugin/pull/184, great
- otherwise, I'm comfortable with a / plan on resolving https://issues.jenkins-ci.org/browse/JENKINS-42276, point upstream jenkins users to the appropriate sync plugin version, and go from there.
- given my prior success running blueocean 1.3.1, I suspect we'll be OK upgrading it in the 3.8/3.9 timeframe as we see fit, but certainly if there is an similar issue we build off of this context and go from there

**Comment by sherl0cks** [comment]
@bparees @bparees @coreydaley I updated https://issues.jenkins-ci.org/browse/JENKINS-42276 with reproducers. https://github.com/sherl0cks/labs-ci-cd/blob/jenkins-42276-latest/s2i-config/jenkins-master/plugins.txt can be used as the basis for #428
