### ISSUE TITLE
Logging into Jenkins sometimes takes a lot of time and massive CPU spikes

### ISSUE THREAD

**Issue by jlebon** [openshift/jenkins#501]
Sometimes when logging into Jenkins from the OpenShift console portal, it takes a really long time to be redirected back to Jenkins, during which the `java` process goes to e.g. 250% usage. Some other times, I'm never even redirected, and I have to kill the pod.

`jstack -l` of the process when stuck: https://gist.github.com/jlebon/fe47831b278f4b5792ff6dd368e92d22

The threads that take up the most CPU time are the four GC ones (at the bottom).

We're using a custom Jenkins image built using S2I: https://github.com/jlebon/projectatomic-ci-infra/tree/master/papr. Reproducer:

```
$ git clone https://github.com/jlebon/projectatomic-ci-infra
$ cd projectatomic-ci-infra/papr
$ oc new-project papr
$ echo "garbage" > token
$ oc secrets new github-token token=token
$ oc new-app --file papr-jenkins.yaml -p REPO_URL=https://github.com/jlebon/projectatomic-ci-infra
$ oc start-build papr-jenkins
```

Once Jenkins is up and running, simply try to login. If it doesn't hang, wipe and try again.

**Comment by gabemontero** [comment]
Yep we know about it.

The need for GC is created because because Jenkins recently added some plugin validation logic (which can include several things, including interaction via http with the jenkins update center).

PR https://github.com/openshift/jenkins/pull/440 is driving this.  To summarize what is there:

1) if this gets too painful, I'm going to disable the update monitor, etc. in our base jenkins image; if folks really want it, they can explicitly enable it and deal with the fall out

not there yet, but we'll see

2) short term workaround, instantiate your jenkins pod with a larger memory limit; this will result in a bigger heap, and reduce the churn you see here ... as an example, at least for my base jenkins image usage, 2 Gi has generally done the trick

3) we'd still like to see if we can tweak the GC settings such that this upfront GC is mitgated .... not sure how optimistic we are (well, at least me)... but it is due diligence item we want to get to before 1) or changing our default template pod mem limit

@bparees @jim-minter FYI ^^^ .... we finally got an external hit on this.

Even with the PR open, I'll leave this open for now, in case users look at issues but not PRs.

**Comment by gabemontero** [comment]
Ok, closing this out with the following

1) openshift 3.9 will have updates to the jenkins templates to help mitigate things
2) we figured out how to do the update center processing on startup vs. on the initial login ... PR https://github.com/openshift/jenkins/pull/440 is implementing that
