### ISSUE TITLE
maven slave v3.6 centos image has incorrect version of oc

### ISSUE THREAD

**Issue by spicysomtam** [openshift/jenkins#504]
This caught me out when I lost context on a maven slave; thought I was logged into a project but oc reported I was on the prior project. Thus I updated the v3.6 slave image with the correct oc version and it fixes the issue for me. Testing:

```
$ docker run -it openshift/jenkins-slave-maven-centos7:v3.6 bash
Using 64 bit Java since OPENSHIFT_JENKINS_JVM_ARCH is not set
bash-4.2$ oc version
oc v1.5.0+031cbe4
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO
bash-4.2$ ^C
bash-4.2$ exit

$ docker run -it openshift/jenkins-slave-maven-centos7:v3.6u1 bash
Using 64 bit Java since OPENSHIFT_JENKINS_JVM_ARCH is not set
bash-4.2$ oc version
oc v3.6.0+c4dd4cf
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO
bash-4.2$ 
```

I did a pull on the image to see if it had been updated.

**Comment by bparees** [comment]
yeah, in the 3.6 timeframe we were manually managing the oc binary included in the images.  starting with 3.7 the images are built on top of the origin base image so they always include a matched oc binary.

Since the v3.5 oc binary is compatible w/ openshift v3.6, we aren't going to go back and publish a new v3.6 image to fix this (we generally don't backport fixes to origin releases).

> This caught me out when I lost context on a maven slave; thought I was logged into a project but oc reported I was on the prior project. Thus I updated the v3.6 slave image with the correct oc version and it fixes the issue for me

What issue did you actually have?  If there is a legitimate problem w/ the v3.5 binary talking to your v3.6 cluster we might consider updating the image, but i haven't heard of any to date (and again for origin we'd more likely just encourage you to update to v3.7)

**Comment by spicysomtam** [comment]
```

**Comment by bparees** [comment]
that's pretty weird and not sure how that would be caused by a v1.5 client talking to a 3.6 cluster, short of a straight up bug in 1.5.

anyway if you can move up to 3.7 i'd recommend that.  if it's really blocking you we can consider updating the v3.6 image but i'd rather avoid that.

**Comment by bparees** [comment]
(also would be interested to see your full Jenkinsfile)

**Comment by spicysomtam** [comment]
Its no blocker; I created a Dockerfile to add the 3.6.0 client to the v3.6 image and tagged it as v3.6u1. We use our own internal docker registry hosted on jfrog artifactory and pull images from there. No big drama. But with the testing I have done, you need to stick to the oc client version for the version of openshift you are running, otherwise you will get some strange behaviour/incompatibilities.

Jenkinsfile is has quite a few steps. code checkout, deploy zookeeper, kafka and local dynamodb, then a  build config to perform multiple scala builds (and tests; hence the zookeeper/kafka/dynamodb to test against). That runs for master and PR's using the github organisation jenkins plugin. If its a master build, further build configs pull built artifacts out of the builder image and generate docker images. There is a custom build to generate an nginx gateway, then a oc login to a dev environment to reimport imagestreams so the freshly built images are deployed to dev via imagestream triggers. The first big builder could do with a volume; docker is horribly slow extending its filesystem and an external volume would make it much quicker (confirmed this using s2i and docker natively; a docker volume makes the build much faster). Could share the Jenkinsfile.

**Comment by bparees** [comment]
yeah i was interested to see the jenkinsfile just in case there was something obvious in there tripping up oc.

Anyway we agree about trying to align your oc client w/ your cluster, though there is supposed to be guaranteed N-1 compatibility (as long as you aren't trying to use new apis w/ an old client of course)

Since you have a workaround i'm going to close this.  Hopefully this problem becomes a non-issue as people move up to v3.7+

**Comment by spicysomtam** [comment]
We are going live soon with an app and have multiple cluster across different data centers. Thus there is very little chance we will upgrade any time soon. So 3.6.0 it is.
