### ISSUE TITLE
RHEL7 Jenkins image : some environment variables do not work

### ISSUE THREAD

**Issue by SpeedBlack** [openshift/jenkins#526]
Hello,

I'm trying to use the RHEL7 Jenkins image. I can't manage to use some environment variables.
I use OCP v3.6 :
```$ oc version
oc v3.6.173.0.83
kubernetes v1.6.1+5115d708d7
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://xxxxx:443
openshift v3.6.173.0.83
kubernetes v1.6.1+5115d708d7
```

I tried without using Openshift (directly with Docker). I have the same problem.
For example, if a try add the "gitlab-oauth" plugin :

1. Run the initial image (volume mount point : /tmp/jenkins2) :
```
sudo docker run -it -e JENKINS_PASSWORD=toto -e OPENSHIFT_JENKINS_JVM_ARCH=i386 -v /tmp/jenkins2:/var/lib/jenkins private-registry:5000/openshift3/jenkins-2-rhel7:v3.6.173.0.96-2
```

2. Run the new custom image with the "OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS" environment variable (always the volume mount point : /tmp/jenkins2)
```
sudo docker run -it -e JENKINS_PASSWORD=toto -e OPENSHIFT_JENKINS_JVM_ARCH=i386 -e OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS=true -v /tmp/jenkins2:/var/lib/jenkins private-registry:5000/openshift3/jenkins-2-rhel7:v3.6.173.0.96-2_1
```

3. For example, the "gitlab-oauth" plugin is not present :
```
ls -la /tmp/jenkins2/plugins | grep gitlab-oauth
```

4. If I try to run custom image directly (for the first time --> new volume mount point : /tmp/jenkins3)
```
sudo docker run -it -e JENKINS_PASSWORD=toto -e OPENSHIFT_JENKINS_JVM_ARCH=i386 -v /tmp/jenkins3:/var/lib/jenkins private-registry:5000/openshift3/spb-jenkins-2-rhel7:v3.6.173.0.96-2_1
```

5. the "gitlab-oauth" plugin is present !
```
ls -la /tmp/jenkins3/plugins | grep gitlab-oauth
drwxr-xr-x.  5 1001 root 4096 Mar  6 10:23 gitlab-oauth
lrwxrwxrwx.  1 1001 root   39 Mar  6 10:23 gitlab-oauth.jpi -> /usr/lib64/jenkins/SPB/gitlab-oauth.hpi
```

I tried with the Centos image and it works correctly.

Can you explain it to me?

Thanks,
Best regards.

**Comment by gabemontero** [comment]
@SpeedBlack can you provide the sha / tag for the rhel7 image you are using?  The versioning works a little different with the rhel vs. centos image (including the latest tag not representing what you think it might)- it is quite possible you are running a rhel image without the support in question here.

**Comment by SpeedBlack** [comment]
Hi @gabemontero 

I tried with two images :
```
registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.6.173.0.96-11 
registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.6.173.0.96-2
```

Thanks !

**Comment by gabemontero** [comment]
OK, this makes sense now @SpeedBlack 

`OVERRIDE_PV_PLUGINS_WITH_IMAGE_PLUGINS` was a feature introduced with our v3.7

It was not back ported to v3.6 nor are their plans to.

You could try the 3.7 rhel image in the interim if you like.  Also, 3.9 should go out sometime this month.

**Comment by SpeedBlack** [comment]
@gabemontero 
hoo, ok, thanks for that clarification !
On the Redhat catalog, the "latest" tag is v3.6.173.0.96-11. That's why I used this image.

Last question:
Can we use v3.7 image (registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.7.23-10) with OCP v3.6 ?
No problem with the 3.7 oc binary available in this image ?

Thansk!
Bests regards

**Comment by gabemontero** [comment]
On Tue, Mar 6, 2018 at 3:48 PM, SpeedBlack <notifications@github.com> wrote:

> @gabemontero <https://github.com/gabemontero>
> hoo, ok, thanks for that clarification !
> On the Redhat catalog, the "latest" tag is v3.6.173.0.96-11. That's why I
> used this image.
>
Yeah this was the "versioning diferences" I was referring to earlier.  With
the rhel images, based
on a migration snafu we had when 3.7 went out, the latest tag points to,
and will continue to point to
for the foreseeable future, to 3.6.

As you start to upgrade your openshift's, you'll soon see that the image
streams and templates now
reference version specific tags instead of latest as a result of all this.


> Last question:
> Can we use v3.7 image (registry.access.redhat.com/
> openshift3/jenkins-2-rhel7:v3.7.23-10) with OCP v3.6 ?
> No problem with the 3.7 oc binary available in this image ?
>
Good question.  There has been some churn in this space.  The oc binary is
suppose to be n-1 compatible.
So yes, the 3.7 oc should be able to talk to 3.6.  It is conceivable though
based on how old your 3.6 is, you
might need to install some 3.6 patches on there for certain things. I tried
to look but did not find a precise list
of those though.

We talk about it at
https://github.com/openshift/jenkins#inclusion-of-the-oc-binary

Certainly keeping them in sync is the ideal.  And you are able to inject
the 3.6 binary into the 3.7 image
using the Jenkins command tools stuff and leverage the 3.6 binary if needed.

The oc binary has not bearing on the env var stuff.
