### ISSUE TITLE
Add support for incremental builds for the Jenkins master

### ISSUE THREAD

**Issue by psiroky** [openshift/jenkins#605]
I would like to speed-up the s2i build of the Jenkins master. Based on my measurements, the longest part of the build, by far, is downloading the plugins. It easily takes like 90% of the time. Would it make sense to add a `save-artifacts` s2i script which would package all the downloaded plugins and if the users enabled incremental builds, the plugins would then be reused in subsequent builds? Not sure if that's supported by the `install-plugins.sh` script, so that could perhaps need some tweaks as well.

WDYT?

**Comment by gabemontero** [comment]
+1 and yes `install_plugins.sh` would need to be tweaked to facilitate this

just to make sure, are you planning on submitting a PR for this @psiroky ?  If so, I'll leave this issue open as is.  Otherwise, our process is to close requests like this and open an associated item on our trello board.

thanks

**Comment by psiroky** [comment]
@gabemontero yes, I would like to take a stab at this. Will keep you posted.

**Comment by psiroky** [comment]
PR with the initial suggested solution: https://github.com/openshift/jenkins/pull/610

**Comment by psiroky** [comment]
I am closing this since the PR #610 was recently merged. The feature should be available in v3.11 (IIUC).
