### ISSUE TITLE
Issues with running npm install in 3.10 node agents

### ISSUE THREAD

**Issue by sbohan** [openshift/jenkins#621]
I have tried both rhel and cent agents now and have the same errors in both.

My build step is simply trying to run npm install, the no package lock is an attempt to fix the issue that didn't work:
```
+ node -v
v8.9.4
+ npm -v
5.6.0
+ npm --registry http://10.xxx.xxx.66:8081/repository/npm-public/ install --no-package-lock
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
npm WARN deprecated mailcomposer@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.9: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN deprecated uws@9.14.0: stop using this version
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated buildmail@4.0.1: This project is unmaintained
npm WARN deprecated socks@1.1.10: If using 2.x branch, please upgrade to at least 2.1.6 to avoid a serious bug with socket data flow and an import issue introduced in 2.1.0
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/neo-async-2fec49e0/rejectLimit.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/lodash-f6ecf004/_baseForOwnRight.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/rxjs-2c33d454/_esm2015/observable/ArrayLikeObservable.js.map'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/less-79e1a882/test/less-bom/mixins-guards-default-func.less'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/@angular/common-6c13086b/locales/en-MH.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/neo-async-2fec49e0/rejectSeries.js'
npm WARN tar Unknown system error -122: Unknown system error -122, open '/home/jenkins/workspace/frontend-build/node_modules/.staging/lodash-f6ecf004/_baseForRight.js'
...repeat -122 error for every package..
```
The install works fine when using both older 3.9 images.

Any ideas?

**Comment by gabemontero** [comment]
Yeah other than the version of node the old and new images are constructed identically.  Definitely feels node version specific.

I personally have minimal node expertise so could not infer any cause from what you are seeing.

Pending responses from other folks tracking this repo, my only suggestion would be to try the v8 node image from https://github.com/sclorg/s2i-nodejs-container in a non-Jenkins deployment and see what happens when you try to perform the same type of build.

That repo also has a v4 nodejs image.

This repo's images should be pulling from the same RPMs as that repo.

If you see similar results from the sclorg images, that would confirm the version theory.  And the sclorg guys are the ones to sort out any node bugs, drive fixes into the RPMs, etc.

**Comment by sbohan** [comment]
An update here, I ran this on my laptop using the exact same package.json within the jenkins agent node image and the 'npm install' worked as expected. Which leaves either the networking layer or somehow the execution environment as the issue.
