### ISSUE TITLE
add skopeo base image

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/jenkins#632]
When using Jenkins in a production setting, the typical approach is to separate non-production cluster from production cluster. I feel like having skopeo baked into the out-of-the-box jenkins image would be nice for consumers. 

What are y'alls thoughts?

**Comment by gabemontero** [comment]
Hey @Gl4di4torRr - I started some polling activity internally to assess this.  `skopeo` certainly falls into an interesting category strategically :-) ... so it is not a slam dunk either way in my mind.

I'll circle back here once I get some feedback.

**Comment by Gl4di4torRr** [comment]
@gabemontero thanks! Let me know. I would be happy to work towards implementing this.

**Comment by gabemontero** [comment]
sure thing @Gl4di4torRr ... yeah, with `skopeo` existing in fedora, etc. most likely the impl would be making sure it has made it all the way to rhel repos so we can `dnf` it.... maybe have to pull a copr repo file for centos.

I've already received some feedback (all positive) ... just awaiting feedback from the right stakeholders.

**Comment by grdryn** [comment]
FWIW I'd also use this...we already install `skopeo` into one of our agent images :)

**Comment by gabemontero** [comment]
OK we got quite the amount of feedback (generally positive for inclusion) from my poll, but in the end, the opinion that matters asked for details about why `oc image mirror` could not be used for the same results for the scenarios in question.

@Gl4di4torRr @grdryn - are either of your familiar with `oc image mirror` and can already relay why it did not sufficiently help you vs. `skopeo`?

Or if you are not familiar, can you run an `oc help image mirror`, look and the help/documentation, and see if that is sufficient for your respective purposes?

**Comment by Gl4di4torRr** [comment]
@gabemontero I have not tried `oc image mirror`. From my understanding, `skopeo` is the mainstream way to promote images. I will test the `oc image mirror`, but testing may take me a minute because I do not have two environments accessible to me right now. I will try and figure that out. Thanks!

**Comment by gabemontero** [comment]
Sounds good @Gl4di4torRr - just let us know any particular pros/cons you come up with whenever you get the chance to try it out.  If some aspect of the scenario is available via `skopeo` but not through `oc image mirror` we can see about arguing for the inclusion of `skopeo` based on that.

**Comment by grdryn** [comment]
I have also never tried (or even heard of) `oc image mirror`, that sounds really useful. Thanks @gabemontero!

**Comment by Gl4di4torRr** [comment]
@gabemontero I was able to get the `oc image mirror` working from cluster to cluster. Initially, I was having issues with authentication. First, I was doing a `docker login -u <USERNAME> -p <OC_TOKEN> <OC_REGISTRY>` and doing the docker pull, tag and push manually. When I went to do the `oc image mirror`, I was still getting authentication issues. I am on a MAC and my auth tokens were being stored inside my macOS keychain. I found [this issue](https://github.com/openshift/origin/issues/19769) and put the auth tokens directly in my `~/.docker/config.json`. I will be discussing the implementation/consequences of this with other engineers. I am not convinced the `oc image mirror` is the best approach. I will let you know though.

**Comment by gabemontero** [comment]
thanks for the update @Gl4di4torRr .... I'll forward a ref to this on the internal email thread we have on this

and yeah, just let me know once you all have your discussion and if any subsequent thoughts arise from that or from additional experimentation

**Comment by smarterclayton** [comment]
Is that specific to docker integration with the Mac keychain?  We could consider adding that to the login flow we have, but does any other client except docker4mac support it?

**Comment by smarterclayton** [comment]
oc image mirror is the codebase that will be used to support innate mirroring of images from OpenShift out to other registries.

**Comment by Gl4di4torRr** [comment]
@smarterclayton are you including an OpenShift registry as other registries?

I have only tested the integration on my Mac.

**Comment by gabemontero** [comment]
glad you got things working @Gl4di4torRr 

it case it was not clear, it will be @smarterclayton 's call not only as to whether we would include `skopeo` in our Jenkins image (though with you making `oc image mirror` work for your scenario that is less likely), but how much additional evangelizing to be done ... note the command is still marked as experimental (see the output from `oc help image mirror)` so that is probably gating some of the doc (there are not hits in docs.openshift.org yet) and evangelizing, but @bparees probably could provide more details there than me (assuming this falls under our internal registry umbrella ... I think it does but could be mis-remembering)

**Comment by bparees** [comment]
docs are coming: https://github.com/openshift/openshift-docs/pull/9381

**Comment by Gl4di4torRr** [comment]
@gabemontero thank you for the clarification and thanks for sharing @bparees

**Comment by grdryn** [comment]
@Gl4di4torRr thanks for the example of how you use it & set up the registry credentials! I was playing around with it a little, and figured a couple of things:

1. I think you can remove the `script {}` block, if you use the `withDockerRegistry` step, rather than the `docker.withRegistry` method:

```
stage('oc image mirror') {
    steps {
        withDockerRegistry([credentialsId: 'cluster1-creds', url: 'https://docker-registry-default.cluster1.ocp.mycompany.com:443']) {
            withDockerRegistry([credentialsId: 'cluster2-creds', url: 'https://docker-registry-default.cluster2.ocp.mycompany.com:443']) {
                sh """
                    oc image mirror --insecure=true docker-registry-default.cluster2.ocp.mycompany.com:443/ci/spring-boot-rest-example:latest docker-registry-default.cluster1.ocp.mycompany.com:443/chris-iac-poc-dvl/spring-boot-rest-example:latest 
                """
            }
        }
    }
}
```

2. In either case, with the plugin versions of `docker-commons` (1.11) and `docker-workflow` (1.9) that are used in the image from this repo, a `.dockercfg` will be created in the home directory of the user in the agent, and it _won't_ be cleaned up when exiting the step/method. I believe this is fixed in newer versions of the plugins ([upstream issue](https://issues.jenkins-ci.org/browse/JENKINS-28702)), but I haven't tried it. It's worth knowing about though, depending on where your pipeline runs (if it's on an executor on the master (or similarly any other persistent agent machines), then it'll be in `/var/lib/jenkins/` or somewhere equivalent, and might be readable by other jobs after.

**Comment by gabemontero** [comment]
If thing continue to trend toward not including `skopeo`, at least at this time, some form of instruction, at least initially in this repo's README, to touch upon this scenario, *could* be warranted.... maybe eventually promote it to docs.openshift.org and cross reference with the doc link @bparees posted.

Opinions around yes/no, exact content if yes, location if yes, etc. are welcome.

**Comment by Gl4di4torRr** [comment]
Yes. I vote for documentation on `oc image mirror` in the README here and doing some cross referencing. I do not mind working implementing something once we get more votes.

**Comment by grdryn** [comment]
+1 to documenting this instead of including skopeo (even though I still have a use case for skopeo, where I upload images from a local tarball rather than a registry).

Do you think something in the `openshift-client` and/or `openshift-pipeline` plugins could be nice?

**Comment by gabemontero** [comment]
thanks @Gl4di4torRr @grdryn 

Some responses
1) on the upload from a local tarball ... not sure that would be sufficient for including skopeo, but I could relay the scenario to the discussion thread on the internal openshift dev mailing list (unless @smarterclayton catches wind of it here) ... is it as simple as it sounds @grdryn , or could you spell out the details a bit?

Certainly documenting the `oc image mirror` scenario could progress regardless of that 

2) `openshift-pipeline` is defunct / maintenance only at best ... wouldn't go there

adding `openshift.imageMirror` etc. could go along with documenting the scenario / cross referencing

3) absolutely if you are up to making the initial foray @Gl4di4torRr go for it ... depending on how @bparees chimes in, that would be sufficient votes in my mind to proceed

**Comment by bparees** [comment]
> If thing continue to trend toward not including skopeo, at least at this time, some form of instruction, at least initially in this repo's README, to touch upon this scenario, could be warranted.... maybe eventually promote it to docs.openshift.org and cross reference with the doc link @bparees posted.

ok with me

> adding openshift.imageMirror etc. could go along with documenting the scenario / cross referencing

definitely longer term but also ok with me.

**Comment by grdryn** [comment]
> on the upload from a local tarball ... not sure that would be sufficient for including skopeo

Yeah, I don't think it's a sufficient reason to include either, it's not a common case. I've got it in one of my custom agent images anyway :)

> `openshift-pipeline` is defunct / maintenance only at best ... wouldn't go there

Good to know, thanks!

**Comment by grdryn** [comment]
I've been playing around with `oc image mirror` in a pipeline, with the intention of publishing an image from an ImageStream to an external docker registry. I'm using the `withDockerRegistry` like in the example discussed above for the external registry, so that gets put into the `~/.dockercfg`. I don't have a Jenkins credential for the internal registry though, and I was hoping that maybe `oc` has enough info already (`oc whoami`, and `oc whoami -t`), but that doesn't seem to be the case (assuming my issue isn't actually that the `jenkins` ServiceAccount (which has the admin role for the project in which the ImageStream is) doesn't have permission to do this):

```
error: unable to retrieve source image docker-registry-default.192.168.42.213.nip.io/jenkins-stage/jenkins by tag latest: unauthorized: authentication required
```

If I understand the problem correctly, then locally I could do a `docker login` to the internal registry, and I imagine that would be enough. In a pipeline, I'd have to ensure that either the docker client is installed in the agent in which the pipeline is running in, or construct the right base64 encoded strings and insert them into the config file. Neither of these seem great, is there an easier way? (semi-related, if I read some Jenkins issues around the `withDockerRegistry` correctly, then newer versions may actually use `docker login` and `docker logout` which might require it to be there anyway)

If I haven't misunderstood, then if there's going to be an `openshift.imageMirror` from the plugin, would it be nice if it was able to use the service account credentials for the internal registry? Would it be useful if `oc` would do that by default (use the logged-in user from the current context as seen by `oc whoami`)? Otherwise, `skopeo copy` might still be more convenient, since one can pass `--src-creds` and `--dest-creds` inline.

I guess for the other direction (from external registry to imagestreamtag) then `oc tag` would be more appropriate, but it doesn't seem to do it for this direction (imagestreamtag -> external registry), does that sound correct?

**Comment by grdryn** [comment]
> Otherwise, skopeo copy might still be more convenient, since one can pass `--src-creds` and `--dest-creds` inline.

Maybe not this part, since `skopeo` appears to break on the colons in `system:serviceaccount:project:jenkins`: https://github.com/projectatomic/skopeo/issues/527

**Comment by bparees** [comment]
> Maybe not this part, since skopeo appears to break on the colons in 

the username doesn't matter when you use a token for authentication (e.g. you can run `docker login -u foobar -p \`oc whoami -t\``)

> If I understand the problem correctly, then locally I could do a docker login to the internal registry, and I imagine that would be enough. In a pipeline, I'd have to ensure that either the docker client is installed in the agent in which the pipeline is running in, or construct the right base64 encoded strings and insert them into the config file. Neither of these seem great, is there an easier way?

I think that's generally correct unfortunately.  You might be able to mount the existing secret in (you have a dockercfg secret in your namespace) and use that since it will already be appropriately formatted, rather than trying to construct a config.json dynamically.

**Comment by grdryn** [comment]
>> Maybe not this part, since skopeo appears to break on the colons in
> 
> the username doesn't matter when you use a token for authentication (e.g. you can run `docker login -u foobar -p $(oc whoami -t)`)

Ooh, that's useful to know, thanks! This solved my issue. I'll use `skopeo` for now, until I see how an `openshift.imageMirror` might look.

**Comment by Gl4di4torRr** [comment]
@gabemontero @grdryn  looping back around on this. I have created a multi cluster pipeline at https://github.com/redhat-cop/container-pipelines/pull/35. Still getting lots of push back on this approach. Should we document image mirror in the readme? If so, how would you like to see it? Or does openshift/openshift-docs#9381 suffice?

**Comment by bparees** [comment]
I don't understand the pushback you got..someone else asked the same question i have:  how is it more tightly coupled than skopeo?  oc mirror image(as i understand it) can push to any registry, whether it's part of a cluster or not.

So i think we still want to resolve this issue by referencing the oc mirror image docs as an "fyi" in the client plugin docs(readme at a minimum, official product docs maybe), and we can also keep it open as an RFE to consider adding a openshift.imageMirror wrapper.

**Comment by Gl4di4torRr** [comment]
@bparees I am not concerned about the push back. I think it just causes change to the image promotion process that will require people to adjust.

Thanks for the info. I will look into adding an fyi next week.

**Comment by Gl4di4torRr** [comment]
@bparees @gabemontero I am not sure if this changes anything, but in the August update I received last night, I found it interesting [this skopeo blog](https://blog.openshift.com/promoting-container-images-between-registries-with-skopeo/) was posted.

**Comment by bparees** [comment]
@jorgemoralespou you should look into "oc mirror image" :)

**Comment by jorgemoralespou** [comment]
@bparees, I love how one learns about new stuff. This is how evangelism can succeed.

Will look into it.

**Comment by bparees** [comment]
@Gl4di4torRr i'm inclined to close this in light of your docs update in https://github.com/openshift/jenkins-client-plugin/pull/175, agree?

**Comment by Gl4di4torRr** [comment]
@bparees i agree. thanks!
