### ISSUE TITLE
container cap in older versions

### ISSUE THREAD

**Issue by Gl4di4torRr** [openshift/jenkins#637]
Would y'all be okay bumping the container cap in 3.7 and 3.9 since those are the most used versions right now?

**Comment by bparees** [comment]
@Gl4di4torRr it doesn't really fulfill the characteristics of something we'd normally backport, but I guess i don't have a strong objection.  Note that it would also need to be backported to 3.10 since the PR merged into our 3.11(master) branch.  3.10 is in codefreeze right now, so it would need to be done after 3.10 GAs.

**Comment by Gl4di4torRr** [comment]
@gabemontero i removed all the jenkins 1 changes. i accidently closed #641 and just pushed the update and opened #642

**Comment by gabemontero** [comment]
no worries @Gl4di4torRr

**Comment by Gl4di4torRr** [comment]
@gabemontero everything is merged. yay! thank you for all your help yesterday updating the packages.

**Comment by gabemontero** [comment]
yw @Gl4di4torRr and thanks again for contributing
