### ISSUE TITLE
Maven Jenkins agents does not set MAVEN_HOME

### ISSUE THREAD

**Issue by markperdue** [openshift/jenkins#691]
Hello,

I am not sure if it is by design but things like MAVEN_HOME and JAVA_HOME are not set in images such as https://access.redhat.com/containers/?tab=tech-details#/registry.access.redhat.com/openshift3/jenkins-agent-maven-35-rhel7

Can these images provide those environment variables out of the box as opposed to requiring the user to set them explicitly through things like `MAVEN_HOME=$(dirname $(dirname "$(which mvn)"))`?

Thanks

**Comment by gabemontero** [comment]
Yeah I feel like there is some history here, but don't recall the specifics at the moment.... maybe @bparees does

**Comment by bparees** [comment]
i also have a vague sense this was deliberate but don't recall any specific reason.

our wildfly image sets java_home (during s2i assemble, but not at runtime) but not maven_home.

setting JAVA_HOME in particular is slightly fiddly because of our logic to use either 32 or 64bit java depending on the container constraints.

**Comment by jim-minter** [comment]
Can't remember, I'm afraid.

**Comment by gabemontero** [comment]
I think I finally found some of the old links I had for research here.  In particluar, check out some of the warnings at 

https://stackoverflow.com/questions/17136324/what-is-the-difference-between-m2-home-and-maven-home

and 

https://stackoverflow.com/questions/26609922/maven-home-mvn-home-or-m2-home

about not needing either as of 3.5 (which our image is at now).

Closing out.
