### ISSUE TITLE
Bare uid in USER instruction leaves root supplementary group

### ISSUE THREAD

**Issue by cgwalters** [openshift/jenkins#7]
```
USER 1001
```

is not a good idea, because:

```
bash-4.2$ id
uid=1000030000 gid=0(root)
```

We should use `useradd` and `groupadd` to add an entry to `/etc/passwd` and `/etc/group` so that there's a supplementary group to use.  E.g.:

```
RUN groupadd -g 1000 jenkins && useradd -u 1000 -g 1000 jenkins
USER jenkins
```

**Comment by cgwalters** [comment]
At present, I'm not seeing an obvious privilege escalation in the current Jenkins image from simply having `gid=0` - however, it does mean that files like the `/run/secrets` with entitlements are readable.

Hmm, actually there already *is* a `jenkins` user created from the RPM, so why aren't we just doing `USER jenkins` ?

**Comment by bparees** [comment]
when images run on openshift, they are assigned a random uid to run as.  so the reason behind not defaulting to the jenkins user is so that we when we test the image outside of openshift, we ensure we aren't running as jenkins (ie ensure the image works when run as a random userid).

had not considered the group side of the equation...  not clear to me why uid=1001 would be in gid 0?  seems strange.

**Comment by bparees** [comment]
we actually now depend on the assumption that the container uid is a member of gid 0, so closing this.

(it's an assumption baked into many of the openshift images, not just the jenkins one)
