### ISSUE TITLE
Kube config file disappears after setting HTTPS_PROXY

### ISSUE THREAD

**Issue by daniyalj** [openshift/jenkins#747]
👋 I am trying to understand an issue I am facing in our staging OpenShift Container Platform environment.

We have a remote artifactory server we want to reach through a proxy with Jenkins to download some files. After setting the https_proxy environment variable in the deployment config, the Jenkins service account gets logged out and the context for oc changes to localhost:8443.

Before setting https_proxy env var:
```
$ oc whoami
system:serviceaccount:cicd:jenkins
```

After setting https_proxy env var:

```
$ oc whoami
Unable to connect to the server: Service Unavailable
```

What's more interesting is that after the https_proxy env var is set, the `~/.kube/config` directory disappears.

I am also able to log in through the jenkins terminal manually with the service account token. But I dont want to do that since this will be a manual step.

Any help would be appreciated!

**Comment by daniyalj** [comment]
![screen shot 2018-11-29 at 10 09 02 am](https://user-images.githubusercontent.com/13129393/49231064-1fa4d780-f3bf-11e8-9c73-42c94b2e0fd7.png)

**Comment by bparees** [comment]
the oc binary respects https_proxy env vars, so if the api server can't be reached via the proxy your'e setting, this would be the expected result.

Anyway this doesn't sound like a jenkins problem.  I would expect you to see the same thing in any other environment where you set a proxy env var and invoke the oc binary.  You will need to find a way to set the proxy env var in a more fine grained way so that it is not set when you are invoking the oc binary.

**Comment by daniyalj** [comment]
@bparees thank you for the answer! I see what you mean, but I just tried it in a separate environment and the entire `~/.kube/config` directory disappears as well.
