### ISSUE TITLE
Update kubernetes plugin

### ISSUE THREAD

**Issue by svenstaro** [openshift/jenkins#768]
The kubernetes plugin that is currently in use is quite old probably many fixes been made since then. Can you update?

**Comment by gabemontero** [comment]
At this point unless a security advisory, dependency chain req,  or a support case comes in that cites a specific bug fixed by a newer version of k8s, we are standing pat.

And of course this image is meant to extended for various things including bumping plugin versions or installing new plugins.

thanks
