### ISSUE TITLE
How to achieve high-availability using Jenkins on OpenShift?

### ISSUE THREAD

**Issue by svenstaro** [openshift/jenkins#777]
I'm currently trying to enable my persistent Jenkins on OpenShift to continue running even when nodes of the cluster go down (for upgrades or otherwise). It is my understanding that this is currently not possible due to the way Jenkins expects its filesystem and the slaves to work.

The slaves only want to connect to a single master and from what I can see they can't failover to other masters. Is there currently a working method of allowing multiple Jenkins masters to work on OpenShift that also allows the slaves to failover to a different master in case the current one goes down?

**Comment by Gl4di4torRr** [comment]
@svenstaro I just make sure everything for Jenkins is defined in the app repo (Jenkins config, jobs, etc.) and then if I ever want to delete and recreate Jenkins elsewhere, I am using [applier](https://github.com/redhat-cop/openshift-applier) to do so. Seems to be working well. If you need logs or something for audit, you can write everything out to something (splunk, sumologic, etc).

**Comment by svenstaro** [comment]
Don't get me wrong. My Jenkins is 100% reproducible. It's just that I want multiple masters running and not conflicting at the same time.

**Comment by gabemontero** [comment]
multiple masters is a generic jenkins issue vs. having some unique element to it from an openshift/jenkins perspective for sure 

if upstream jenkins has recipes for it, I'm unaware of it ... if someone found them, we could look and see if running jenkins in openshift has friction points with whatever is proscribed

at this time, I would consider the notion beyond the scope of what we are concerned with in this repo wrt openshift/jenkins integration

**Comment by gabemontero** [comment]
Yeah looks like cloudbees enterprise (i.e. the jenkins you buy) has the high availability plugin, and the guys at openstack have implemented a gearman plugin for sharable slaves.

In line with my earlier comment, both are orthogonal to what this repo's focus, other than in theory you could extend the master image from this repo to try out something like the gearman plugin perhaps to achieve the the multiple masters running / not colliding fashion you are noting @svenstaro .

Given the upstream direction of serverless jenkins / jenkins-x running on k8s I see that as the strategic direction, and hence prioritizing tackling your multi-master running at the same time; otherwise, as you probably anticipated, the notion of HA here only goes as far as openshift restarting a down jenkins running off a PV, where you have periods of unavailability before becoming available again.

@siamaksade @sspeiche FYI re: devtools mission in this space
