### ISSUE TITLE
With S2I, manage dynamic part in job config

### ISSUE THREAD

**Issue by YannMoisan** [openshift/jenkins#80]
I've created a template that uses a S2I build to copy job definitions.

When I create a new-app from this template, I need a way to set the token in the configuration of the job. 

Is there a way to modify the source to replace a placeholder ?

Or another way to achieve that use case ?

**Comment by bparees** [comment]
If I understand correctly you have a git repository that contains your
Jenkins job definition, and an openshift template that defines an s2i build
config which uses the repository to create a new Jenkins image with your
job defined in it?

And you want to, at template instantiation, customize the Jenkins job
definition that is being injected into the newly built Jenkins image? (or a
customize it at build time rather than at template instantiation?)

I don't think there's a direct way (especially at template instantiation),
but you might be able to do it via env variables and possibly a customized
assemble script.

Can you show me your template and git repository content? It might help me
understand the scenario.

Ben Parees | OpenShift

**Comment by YannMoisan** [comment]
You get the point perfectly.

I can't show because I'm not working on public stuff.

I was wondering if there is a way without modifying the jenkins image, but I'll try to do that.

**Comment by bparees** [comment]
you don't have to modify the image, you can provide a customized assemble script in your source repo (the same one containing your job configs).
https://docs.openshift.org/latest/dev_guide/builds.html#override-builder-image-scripts

**Comment by bparees** [comment]
@YannMoisan anything further we can help you with here?

**Comment by bparees** [comment]
closing based on lack of feedback, will reopen if needed.
