### ISSUE TITLE
How to add scripts to init.groovy.d?

### ISSUE THREAD

**Issue by adam-sandor** [openshift/jenkins#843]
I'm trying to add some more groovy init scripts to my Jenkins image. I copy the scripts to `/opt/openshift/configuration/init.groovy.d/` where the update-center-init.groovy script already lives. This however doesn't seem to solve it, none of the scripts (including the update-center-init) seem to be picked up.

```
FROM openshift3/jenkins-2-rhel7:v3.11.98
COPY contrib/jenkins/* /opt/openshift/configuration/init.groovy.d/
```

The only solution I could find was to add these lines to the `run` script, but that is very ugly as it requires forking the whole script:
```
rm -rf ${JENKINS_HOME}/init.groovy.d
mkdir -p ${JENKINS_HOME}/init.groovy.d
cp /opt/openshift/configuration/init.groovy.d/* ${JENKINS_HOME}/init.groovy.d
```

Is there an "official" way to add groovy scripts to the image?

**Comment by gabemontero** [comment]
Hey @adam-sandor 

We can see about adding a specific example wrt adding groovy scripts in the docs, but in general the two options documented at 
- https://github.com/openshift/jenkins#installing-using-layering
- https://github.com/openshift/jenkins#installing-using-s2i-build

are the official methods.

Taking what you provided, I was able to modify it and get it to work (it falls under the "layering" approach).  Here are the steps ... I basically replicated more exactly this images dir structure.  From any clean directory:

1) `mkdir -p contrib/openshift/configuration/init.groovy.d`
2) `touch contrib/openshift/configuration/init.groovy.d/foo.groovy`
3) create a Dockerfile with (adjusting the image ref as you see fit)
```
FROM registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.11
COPY ./contrib/openshift /opt/openshift
```
4) `docker build -t gmontero/test-add-groovy:latest .`
5) `docker run -p 8080:8080 -it gmontero/test-add-groovy:latest `
6) then in another window, run `docker ps` to get the container id
7) and then run `docker exec <container id> ls -la /var/lib/jenkins/init.groovy.d`
8) in my example, I got:
```
$ docker exec 391436fa158b ls -la /var/lib/jenkins/init.groovy.d
total 12
drwxr-xr-x.  2 default root 4096 May  2 18:47 .
drwxrwxr-x. 15 jenkins root 4096 May  2 18:47 ..
-rw-r--r--.  1 default root    0 May  2 18:47 foo.groovy
-rw-r--r--.  1 default root 1154 May  2 18:47 update-center-init.groovy
$
```

Ultimately, this line then does the copy you need:  https://github.com/openshift/jenkins/blob/openshift-3.11/2/contrib/s2i/run#L376

Not knowing what you have under `contrib/jenkins`, or the fact that you used that instead of what we exactly have under this repo ... namely `contrib/openshift/configuration/init.groovy.d` is what tripped things up.

Let me know if following my precise recipe above doesn't get what is desired for you.

**Comment by adam-sandor** [comment]
Hi Gabe, thank you so much for your super-detailed answer! Sorry I didn't have time to look into it yet, I will test your suggestion asap.

**Comment by adam-sandor** [comment]
So I figured out where things are going wrong. I was putting the groovy files in the right place, but the issue is in the case when the Jenkins is using a persistent volume for `/var/lib/jenkins`. In that case the existing script files don't get overwritten. What do you think, is this a bug or expected behaviour? I'm not sure, as `/var/lib/jenkins` can be modified from the GUI of Jenkins, but the scripts are not like build jobs, to be managed by the user. But because they live in that directory they are subject to persistence like the jobs and settings.

**Comment by gabemontero** [comment]
expected behavior @adam-sandor 

the image only does the config copy once, and then places a file in /var/lib/jenkins that tells it it that it did the copy.

yeah, I've had discussion with plenty of other openshift/jenkins users, and recycling their PVs/PVCs in such scenarios is an understood thing.

In conjunction with the doc update I mentioned in https://github.com/openshift/jenkins/issues/843#issuecomment-488793231 we could do a better job of explaining that.

wdyt ?

**Comment by adam-sandor** [comment]
Thanks @gabemontero ! Yeah this makes sense. It's just that in this case, we don't have any way to roll out new versions of the groovy scripts right? Didn't anyone run into this problem before us?

**Comment by kchri-nets** [comment]
We have a small script running through relevant namespaces/jenkins pods that syncs a init.groovy folder into a destination  folder
basically just doing oc -n my-ns rsync --delete ./init.groovy.d/ my-pod:/var/lib/jenkins/init.groovy.d/

Could be nice to to have this added to the run script and enabled through a environment var similar to how plugin overwrite/migration

**Comment by adam-sandor** [comment]
In our case I consider the groovy scripts to be part of the image. They are not to be stored and managed by the user of Jenkins but by my team who is releasing the Jenkins image. So we want to be able to create new script files, delete and update old ones when the new image is redeployed.
I think the ideal solution would be to have a directory that is outside of `/var/lib/jenkins` that also is treated the same way like `/var/lib/jenkins/init.groovy.d` - all scripts in there get executed at startup. That way the sanctity of `/var/lib/jenkins` would be preserved, while at the same time it would be possible to tweak your image using groovy scripts. Not sure if this is possible with Jenkins though..

**Comment by gabemontero** [comment]
PR with doc updates up

**Comment by adam-sandor** [comment]
We just had a discussion in the team about this because we ran into a similar problem with plugins. What we would like to have both for plugins and init scripts is to be able to supply and update our own in the image while at the same time letting our users running their Jenkinses add their own. I think this could be accomplished with a few parameters to the `run` script. I will discuss with my team to create a PR for upstream. Does that sound like a good idea in line with general design principles for Openshift Jenkins?

**Comment by gabemontero** [comment]
On Sat, Jun 15, 2019 at 6:40 AM Ádám Sándor <notifications@github.com>
wrote:

> We just had a discussion in the team about this because we ran into a
> similar problem with plugins. What we would like to have both for plugins
> and init scripts is to be able to supply and update our own in the image
> while at the same time letting our users running their Jenkinses add their
> own. I think this could be accomplished with a few parameters to the run
> script. I will discuss with my team to create a PR for upstream. Does that
> sound like a good idea in line with general design principles for Openshift
> Jenkins?
>

We’ve generally wanted to put a halt to additional parameters and
customization via the existing run script.

Certainly we will consider PR contributions from our open source users.
But the bar will be high as to how complex the change is before we agree to
merge.

But an actual PR will be the best way to convince us it is simple.

@akram @waveywaves

**Comment by adam-sandor** [comment]
That makes sense, I'll get back to you on this once we have a PR ready and then we can see if it's useful for the upstream project. Thanks for the help so far!
